name: wigilabs
description: Wigilabs test
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  sqflite: ^2.0.2
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.5

flutter_native_splash:
  image: assets/logo_splash.png
  color: '#FFFFFF'

flutter:
  uses-material-design: true
  assets:
    - assets/